name: Continuous Integration

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 16
        cache: maven

    - name: Build by Maven
      run: mvn -B package --file pom.xml

    - name: Build site
      run: |
        version=$(curl -SsL https://git.io/stable-bee)
        curl -SsL -o bee.jar https://jitpack.io/com/github/teletha/bee/${version}/bee-${version}.jar
        java -javaagent:bee.jar -cp bee.jar bee.Bee install doc:site

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/site
